spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: PharmaciesMOneDB

server:
  error:
    include-stacktrace: never

#logging:
#  level:
#    org:
#      hibernate:
#        SQL: DEBUG
#        type:
#          descriptor:
#            sql:
#              BasicBinder: TRACE
