spring:
  datasource:
    url: >
      jdbc:mysql://localhost:3306/pharmacies?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
      &useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true
    username: developer
    password: developer
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: true
  liquibase:
    change-log: classpath:liquibase/liquibase-changeLog.mysql.sql

management:
  endpoints:
    web:
      base-path: '/api/actuator'

springdoc:
  cache:
    disabled: true
  show-actuator: true
  writer-with-default-pretty-printer: true
  group-configs[0]:
    group: "api"
    paths-to-match: "/api/**"

server:
  error:
    include-message: always
    include-stacktrace: never
  port: 8080

logging:
  level:
    org:
      #      hibernate:
      #        SQL: DEBUG
      #        type:
      #          descriptor:
      #            sql:
      #              BasicBinder: TRACE
      apache:
        http: off
      htmlunit: off

---

spring:
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    open-in-view: false
    database: h2
    generate-ddl: false
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  liquibase:
    enabled: false
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  cache:
    type: NONE
  config:
    activate:
      on-profile: testing
