changeLogFile: src/main/resources/liquibase/liquibase-changeLog.mysql.sql
diffChangeLogFile: src/main/resources/liquibase/liquibase-changeLog.mysql.sql
outputChangeLogFile: src/main/resources/liquibase/liquibase-new-changeLog.mysql.sql
url: jdbc:mysql://localhost:3306/pharmacies?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true
defaultSchemaName: pharmacies
username: developer
password: developer
driver: com.mysql.jdbc.Driver
referenceDefaultSchemaName: pharmacies
referenceDriver: liquibase.ext.hibernate.database.connection.HibernateDriver
referenceUrl: hibernate:spring:com.dstym.pharmaciesondutyattica.entity?dialect=org.hibernate.dialect.MySQLDialect
