changeLogFile: src/main/resources/liquibase/liquibase-changeLog.yaml
diffChangeLogFile: src/main/resources/liquibase/liquibase-changeLog.yaml
outputChangeLogFile: src/main/resources/liquibase/liquibase-new-changeLog.yaml
url: jdbc:mysql://localhost:3306/pharmacies
defaultSchemaName: pharmacies
username: developer
password: developer
driver: com.mysql.jdbc.Driver
referenceDefaultSchemaName: pharmacies
referenceDriver: liquibase.ext.hibernate.database.connection.HibernateDriver
referenceUrl: hibernate:spring:com.dstym.pharmaciesondutyattica.entity?dialect=org.hibernate.dialect.MySQL8Dialect&hibernate.physical_naming_strategy=org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy&hibernate.implicit_naming_strategy=org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
